package com.doomviewer.game.objects;

// Concordance with info.c S_XXX indices
public enum StateNum {
    S_NULL, S_LIGHTDONE, S_PUNCH, S_PUNCHDOWN, S_PUNCHUP, S_PUNCH1, S_PUNCH2, S_PUNCH3, S_PUNCH4, S_PUNCH5,
    //S_PISTOL, S_PISTOLDOWN, S_PISTOLUP, S_PISTOL1, S_PISTOL2, S_PISTOL3, S_PISTOL4, S_PISTOLFLASH,
    //S_SGUN, S_SGUNDOWN, S_SGUNUP, S_SGUN1, S_SGUN2, S_SGUN3, S_SGUN4, S_SGUN5, S_SGUN6, S_SGUN7, S_SGUN8, S_SGUN9, S_SGUNFLASH1, S_SGUNFLASH2,
    // ... many more states ...
    // Player states
    S_PLAY, S_PLAY_RUN1, S_PLAY_RUN2, S_PLAY_RUN3, S_PLAY_RUN4, S_PLAY_ATK1, S_PLAY_ATK2, S_PLAY_PAIN, S_PLAY_PAIN2,
    S_PLAY_DIE1, S_PLAY_DIE2, S_PLAY_DIE3, S_PLAY_DIE4, S_PLAY_DIE5, S_PLAY_DIE6, S_PLAY_DIE7,
    S_PLAY_XDIE1, S_PLAY_XDIE2, S_PLAY_XDIE3, S_PLAY_XDIE4, S_PLAY_XDIE5, S_PLAY_XDIE6, S_PLAY_XDIE7, S_PLAY_XDIE8, S_PLAY_XDIE9,

    // MT_POSSESSED (Zombieman) states: index 160 onwards
    S_POSS_STND, S_POSS_STND2, S_POSS_RUN1, S_POSS_RUN2, S_POSS_RUN3, S_POSS_RUN4, S_POSS_RUN5, S_POSS_RUN6, S_POSS_RUN7, S_POSS_RUN8,
    S_POSS_ATK1, S_POSS_ATK2, S_POSS_ATK3,
    S_POSS_PAIN, S_POSS_PAIN2,
    S_POSS_DIE1, S_POSS_DIE2, S_POSS_DIE3, S_POSS_DIE4, S_POSS_DIE5,
    S_POSS_XDIE1, S_POSS_XDIE2, S_POSS_XDIE3, S_POSS_XDIE4, S_POSS_XDIE5, S_POSS_XDIE6, S_POSS_XDIE7, S_POSS_XDIE8, S_POSS_XDIE9,
    S_POSS_RAISE1, S_POSS_RAISE2, S_POSS_RAISE3, S_POSS_RAISE4,

    // MT_SHOTGUY (Sergeant) states: index 187 onwards
    S_SPOS_STND, S_SPOS_STND2, S_SPOS_RUN1, S_SPOS_RUN2, S_SPOS_RUN3, S_SPOS_RUN4, S_SPOS_RUN5, S_SPOS_RUN6, S_SPOS_RUN7, S_SPOS_RUN8,
    S_SPOS_ATK1, S_SPOS_ATK2, S_SPOS_ATK3,
    S_SPOS_PAIN, S_SPOS_PAIN2,
    S_SPOS_DIE1, S_SPOS_DIE2, S_SPOS_DIE3, S_SPOS_DIE4, S_SPOS_DIE5,
    S_SPOS_XDIE1, S_SPOS_XDIE2, S_SPOS_XDIE3, S_SPOS_XDIE4, S_SPOS_XDIE5, S_SPOS_XDIE6, S_SPOS_XDIE7, S_SPOS_XDIE8, S_SPOS_XDIE9,
    S_SPOS_RAISE1, S_SPOS_RAISE2, S_SPOS_RAISE3, S_SPOS_RAISE4, S_SPOS_RAISE5,

    // MT_TROOP (Imp) states: index 455 onwards
    S_TROO_STND, S_TROO_STND2, S_TROO_RUN1, S_TROO_RUN2, S_TROO_RUN3, S_TROO_RUN4, S_TROO_RUN5, S_TROO_RUN6, S_TROO_RUN7, S_TROO_RUN8,
    S_TROO_ATK1, S_TROO_ATK2, S_TROO_ATK3,
    S_TROO_MISS1, S_TROO_MISS2, S_TROO_MISS3,
    S_TROO_PAIN, S_TROO_PAIN2,
    S_TROO_DIE1, S_TROO_DIE2, S_TROO_DIE3, S_TROO_DIE4, S_TROO_DIE5, S_TROO_DIE6,
    S_TROO_XDIE1, S_TROO_XDIE2, S_TROO_XDIE3, S_TROO_XDIE4, S_TROO_XDIE5, S_TROO_XDIE6, S_TROO_XDIE7, S_TROO_XDIE8,
    S_TROO_RAISE1, S_TROO_RAISE2, S_TROO_RAISE3, S_TROO_RAISE4, S_TROO_RAISE5,

    // MT_SERGEANT (Demon) states: index 484 onwards
    S_SARG_STND, S_SARG_STND2, S_SARG_RUN1, S_SARG_RUN2, S_SARG_RUN3, S_SARG_RUN4, S_SARG_RUN5, S_SARG_RUN6, S_SARG_RUN7, S_SARG_RUN8,
    S_SARG_ATK1, S_SARG_ATK2, S_SARG_ATK3, S_SARG_ATK4,
    S_SARG_PAIN, S_SARG_PAIN2,
    S_SARG_DIE1, S_SARG_DIE2, S_SARG_DIE3, S_SARG_DIE4, S_SARG_DIE5, S_SARG_DIE6,
    S_SARG_RAISE1, S_SARG_RAISE2, S_SARG_RAISE3, S_SARG_RAISE4, S_SARG_RAISE5, S_SARG_RAISE6,
    
    // MT_HEAD (Cacodemon) states
    S_HEAD_STND, S_HEAD_RUN1, S_HEAD_ATK1, S_HEAD_ATK2, S_HEAD_ATK3,
    S_HEAD_PAIN, S_HEAD_PAIN2, S_HEAD_PAIN3,
    S_HEAD_DIE1, S_HEAD_DIE2, S_HEAD_DIE3, S_HEAD_DIE4, S_HEAD_DIE5, S_HEAD_DIE6,
    S_HEAD_RAISE1, S_HEAD_RAISE2, S_HEAD_RAISE3, S_HEAD_RAISE4, S_HEAD_RAISE5, S_HEAD_RAISE6,
    
    // MT_BRUISER (Baron of Hell) states
    S_BOSS_STND, S_BOSS_STND2, S_BOSS_RUN1, S_BOSS_RUN2, S_BOSS_RUN3, S_BOSS_RUN4, S_BOSS_RUN5, S_BOSS_RUN6, S_BOSS_RUN7, S_BOSS_RUN8,
    S_BOSS_ATK1, S_BOSS_ATK2, S_BOSS_ATK3,
    S_BOSS_PAIN, S_BOSS_PAIN2,
    S_BOSS_DIE1, S_BOSS_DIE2, S_BOSS_DIE3, S_BOSS_DIE4, S_BOSS_DIE5, S_BOSS_DIE6, S_BOSS_DIE7,
    S_BOSS_RAISE1, S_BOSS_RAISE2, S_BOSS_RAISE3, S_BOSS_RAISE4, S_BOSS_RAISE5, S_BOSS_RAISE6, S_BOSS_RAISE7,
    
    // MT_KNIGHT (Hell Knight) states - similar to Baron
    S_BOS2_STND, S_BOS2_STND2, S_BOS2_RUN1, S_BOS2_RUN2, S_BOS2_RUN3, S_BOS2_RUN4, S_BOS2_RUN5, S_BOS2_RUN6, S_BOS2_RUN7, S_BOS2_RUN8,
    S_BOS2_ATK1, S_BOS2_ATK2, S_BOS2_ATK3,
    S_BOS2_PAIN, S_BOS2_PAIN2,
    S_BOS2_DIE1, S_BOS2_DIE2, S_BOS2_DIE3, S_BOS2_DIE4, S_BOS2_DIE5, S_BOS2_DIE6, S_BOS2_DIE7,
    S_BOS2_RAISE1, S_BOS2_RAISE2, S_BOS2_RAISE3, S_BOS2_RAISE4, S_BOS2_RAISE5, S_BOS2_RAISE6, S_BOS2_RAISE7,
    
    // MT_SKULL (Lost Soul) states
    S_SKULL_STND, S_SKULL_STND2, S_SKULL_RUN1, S_SKULL_RUN2,
    S_SKULL_ATK1, S_SKULL_ATK2, S_SKULL_ATK3, S_SKULL_ATK4,
    S_SKULL_PAIN, S_SKULL_PAIN2,
    S_SKULL_DIE1, S_SKULL_DIE2, S_SKULL_DIE3, S_SKULL_DIE4, S_SKULL_DIE5, S_SKULL_DIE6,
    
    // MT_CHAINGUY (Chaingunner) states
    S_CPOS_STND, S_CPOS_STND2, S_CPOS_RUN1, S_CPOS_RUN2, S_CPOS_RUN3, S_CPOS_RUN4, S_CPOS_RUN5, S_CPOS_RUN6, S_CPOS_RUN7, S_CPOS_RUN8,
    S_CPOS_ATK1, S_CPOS_ATK2, S_CPOS_ATK3, S_CPOS_ATK4,
    S_CPOS_PAIN, S_CPOS_PAIN2,
    S_CPOS_DIE1, S_CPOS_DIE2, S_CPOS_DIE3, S_CPOS_DIE4, S_CPOS_DIE5, S_CPOS_DIE6, S_CPOS_DIE7,
    S_CPOS_XDIE1, S_CPOS_XDIE2, S_CPOS_XDIE3, S_CPOS_XDIE4, S_CPOS_XDIE5, S_CPOS_XDIE6,
    S_CPOS_RAISE1, S_CPOS_RAISE2, S_CPOS_RAISE3, S_CPOS_RAISE4,
    
    // Big enemies - Cyberdemon & Spider Mastermind
    S_CYBER_STND, S_CYBER_STND2, S_CYBER_RUN1, S_CYBER_RUN2, S_CYBER_RUN3, S_CYBER_RUN4, S_CYBER_RUN5, S_CYBER_RUN6, S_CYBER_RUN7, S_CYBER_RUN8,
    S_CYBER_ATK1, S_CYBER_ATK2, S_CYBER_ATK3, S_CYBER_ATK4, S_CYBER_ATK5, S_CYBER_ATK6,
    S_CYBER_PAIN, S_CYBER_DIE1, S_CYBER_DIE2, S_CYBER_DIE3, S_CYBER_DIE4, S_CYBER_DIE5, S_CYBER_DIE6, S_CYBER_DIE7, S_CYBER_DIE8, S_CYBER_DIE9, S_CYBER_DIE10,
    
    S_SPID_STND, S_SPID_STND2, S_SPID_RUN1, S_SPID_RUN2, S_SPID_RUN3, S_SPID_RUN4, S_SPID_RUN5, S_SPID_RUN6, S_SPID_RUN7, S_SPID_RUN8, S_SPID_RUN9, S_SPID_RUN10, S_SPID_RUN11, S_SPID_RUN12,
    S_SPID_ATK1, S_SPID_ATK2, S_SPID_ATK3, S_SPID_ATK4,
    S_SPID_PAIN, S_SPID_PAIN2,
    S_SPID_DIE1, S_SPID_DIE2, S_SPID_DIE3, S_SPID_DIE4, S_SPID_DIE5, S_SPID_DIE6, S_SPID_DIE7, S_SPID_DIE8, S_SPID_DIE9, S_SPID_DIE10, S_SPID_DIE11,

    // Projectile states
    // MT_TROOPSHOT (Imp fireball) states
    S_TBALL1, S_TBALL2, S_TBALLEX1, S_TBALLEX2, S_TBALLEX3,
    
    // MT_PUFF (Bullet impact) states  
    S_PUFF1, S_PUFF2, S_PUFF3, S_PUFF4,
    
    // MT_BLOOD (Blood splat) states
    S_BLOOD1, S_BLOOD2, S_BLOOD3,

    // Weapon states (following original Doom naming)
    // Pistol states
    S_PISTOL, S_PISTOL1, S_PISTOL2, S_PISTOL3, S_PISTOL4,
    S_PISTOLFLASH,
    
    // Shotgun states  
    S_SGUN, S_SGUN1, S_SGUN2, S_SGUN3, S_SGUN4, S_SGUN5, S_SGUN6, S_SGUN7, S_SGUN8, S_SGUN9,
    S_SGUNFLASH1, S_SGUNFLASH2,
    
    // Chaingun states
    S_CHAIN, S_CHAIN1, S_CHAIN2, S_CHAIN3,
    S_CHAINFLASH1, S_CHAINFLASH2,
    
    // Rocket launcher states
    S_MISSILE, S_MISSILE1, S_MISSILE2, S_MISSILE3,
    S_MISSILEFLASH1, S_MISSILEFLASH2, S_MISSILEFLASH3, S_MISSILEFLASH4,
    
    // Plasma states
    S_PLASMA, S_PLASMA1, S_PLASMA2,
    S_PLASMAFLASH1, S_PLASMAFLASH2,
    
    // BFG states
    S_BFG, S_BFG1, S_BFG2, S_BFG3, S_BFG4,
    S_BFGFLASH1, S_BFGFLASH2,

    // Item states
    S_STIM, S_MEDI, S_ARM1, S_ARM2, S_BON1, S_BON2, 
    S_BKEY, S_RKEY, S_YKEY, S_BSKU, S_RSKU, S_YSKU,
    S_CLIP, S_AMMO, S_ROCK, S_BROK, S_CELL, S_CELP, S_SHEL, S_SBOX, S_BPAK,
    
    // Decoration states
    S_BAR1, S_BEXP, S_BEXP2, S_BEXP3, S_BEXP4, S_BEXP5,
    S_FCAN, S_CAND, S_CBRA, S_COL1, S_COL2, S_COL3, S_COL4, S_COL5, S_COL6,
    S_TRE1, S_TRE2, S_ELEC, S_CEYE, S_FSKU,
    S_SMIT, S_SMBT, S_SMGT, S_SMRT, S_COLU, S_SMT2,
    S_GOR1, S_GOR2, S_GOR3, S_GOR4, S_GOR5,
    S_POL1, S_POL2, S_POL3, S_POL4, S_POL5, S_POL6,
    S_HDB1, S_HDB2, S_HDB3, S_HDB4, S_HDB5, S_HDB6,
    S_POB1, S_POB2, S_BRS1, S_TLMP, S_TLP2,
    
    // Special invisible state for spawn points
    S_INVISIBLE,

    // ... placeholder for further states
    S_DUMMY_END_STATE_FOR_NOW
}