package com.doomengine.game.objects;

// Concordance with info.c MT_XXX indices
public enum MobjType {
    MT_PLAYER, MT_POSSESSED, MT_SHOTGUY, MT_VILE, MT_FIRE, MT_UNDEAD, MT_TRACER, MT_SMOKE, MT_FATSO, MT_FATSHOT,
    MT_CHAINGUY, MT_TROOP, MT_SERGEANT, MT_SHADOWS, MT_HEAD, MT_BRUISER, MT_BRUISERSHOT, MT_KNIGHT, MT_SKULL,
    MT_SPIDER, MT_BABY, MT_CYBORG, MT_PAIN, MT_WOLFSS, MT_KEEN, MT_BOSSBRAIN, MT_BOSSSPIT, MT_BOSSTARGET,
    MT_SPAWNSHOT, MT_SPAWNFIRE, MT_BARREL, MT_TROOPSHOT, MT_HEADSHOT, MT_ROCKET, MT_PLASMA, MT_BFG, MT_ARACHPLAZ,
    MT_PUFF, MT_BLOOD, MT_TFOG, MT_IFOG, MT_TELEPORTMAN, MT_EXTRABFG,
    
    // Items and pickups
    MT_CLIP, MT_SHOTGUN, MT_CHAINGUN, MT_MISSILE, MT_PLASMA_RIFLE, MT_CHAINSAW, MT_SUPERSHOTGUN,
    MT_STIMPACK, MT_MEDIKIT, MT_SOULSPHERE, MT_INVULNERABILITY, MT_BERSERK, MT_INVISIBILITY,
    MT_SUIT, MT_COMPUTER_MAP, MT_LIGHT_AMP, MT_MEGAARMOR, MT_GREENARMOR,
    MT_BLUEKEY, MT_YELLOWKEY, MT_REDKEY, MT_BLUESKULL, MT_YELLOWSKULL, MT_REDSKULL,
    MT_CELL, MT_CELLPACK, MT_AMMO, MT_AMMOBOX, MT_SHELLS, MT_SHELLBOX, MT_BACKPACK,
    MT_HEALTH_BONUS, MT_ARMOR_BONUS,
    
    // Decorations and environment
    MT_BARREL_EXPLOSIVE, MT_TECHPILLAR, MT_CANDLESTICK, MT_CANDELABRA, MT_BLOODPOOL,
    MT_IMPALED_HUMAN, MT_TWITCHING_IMPALED, MT_SKULL_ON_POLE, MT_SKULLS, MT_HANGING_VICTIM,
    MT_HANGING_ARMS, MT_HANGING_LEG, MT_HANGING_TORSO, MT_HANGING_HEAD, MT_DEAD_MARINE,
    MT_DEAD_ZOMBIE, MT_DEAD_DEMON, MT_DEAD_CACODEMON, MT_DEAD_IMP, MT_POOL_BLOOD_1,
    MT_POOL_BLOOD_2, MT_POOL_BRAINS, MT_EVIL_EYE, MT_FLOATING_SKULL, MT_BURNING_BARREL,
    MT_TALL_GREEN_PILLAR, MT_SHORT_GREEN_PILLAR, MT_TALL_RED_PILLAR, MT_SHORT_RED_PILLAR,
    MT_BROWN_STUB, MT_TALL_BROWN_PILLAR, MT_SHORT_BROWN_PILLAR, MT_GRAY_TREE, MT_LARGE_BROWN_TREE,
    
    // Multiplayer starts and special objects
    MT_DEATHMATCH_START, MT_TELEPORTER_DEST, MT_TELEPORTER_EXIT,
    
    MT_MAX // Placeholder for array sizing if needed
}